### ISSUE TITLE
Language and dub

### ISSUE THREAD

**Issue by Drac1652** [ErickLimaS/anime-website#77] opened 2024-06-06 00:19 UTC
Thanks for the updates, i need to report some bugs
1. The homepage still hasn't changed language it's still in romanji and also the most popular animes still can't be selected. If you click them nothing happens
2. Gogoanime dub version alert. (Each new episode causes the alert to display, you can make an option to never show this again, this will help both to notify someone that it maybe another anime but also make the next episode play simultaneously.
3. Aniplay dub link is still broken, the next episode plays subbed even if you played the previous episode in dub.
4. If the anime is in keep watching can't be deleted and also if episodes are many and cover the whole screen size cannot be scrolled to see all of them instead it stucks only to the screen size (this is on pc)

**Comment by ErickLimaS** [comment] 2024-06-06 04:38
Language is fixed now (i hope...) and it only wont work on Search Page, because it uses a offline DB to reduce the usage of the Anilist api and avoid getting a 429 error (request limit rate).

The Alert one is a good suggestion, will for sure add later.

> Aniplay dub link is still broken... 

This one is tricking me. Can you give some details? Like, you watch the episode till the end, then it auto play the next one and its subbed? I need to know so i can look exactly where the problem is...

> If the anime is in keep watching can't be deleted and also if episodes are many and cover the whole screen size cannot be scrolled to see all of them instead it stucks only to the screen size (this is on pc)

Delete btn is now fixed. But the scroll thing, you say the scroll bar is not showing or its not scrolling at all?

**Comment by Drac1652** [comment] 2024-06-06 04:50
Aniplay starts a new episode as subbed even if you were watching dubbed
version
Also the scroll thing for watching anime doesn't allow scrolling and the
bar isn't there at all

**Comment by ErickLimaS** [comment] 2024-06-06 21:43
> Aniplay starts a new episode as subbed even if you were watching dubbed
version

I think its fixed now, give a look. If its still broken, tell me exactly what you do when visit the website, from the very start till you get to the waching page.

>Also the scroll thing for watching anime doesn't allow scrolling and the
bar isn't there at all

Its working fine for me. I tested it on mobile, firefox, edge, chrome... Its just drag the list to one side. Maybe its a browser problem. Can you tell me which one you're using?

**Comment by Drac1652** [comment] 2024-06-06 22:38
Am using firefox
Am sending you a picture,
Look for the cursor pointer that's where it stucks i can't navigate the
rest of keep watching beyond that point

**Comment by Drac1652** [comment] 2024-06-06 22:40
![20240607_013619](https://github.com/ErickLimaS/anime-website/assets/137118771/125abde7-2555-4dcc-bce6-970c4f5c622b)

**Comment by ErickLimaS** [comment] 2024-06-07 02:48
Man, i really cant reproduce this bug... Have you tried in other browsers? Whats your screen size?

I still gonna try to find what is causing this problem, but for now you can bypass this just clicking on the Keep Watching Heading then pressing TAB till it show the episode/movie you were watching.

**Comment by Drac1652** [comment] 2024-06-07 16:47
Hellow, about the language change, the language displaying while playing anime is still romanji and that at keep watching also is romanji

**Comment by ErickLimaS** [comment] 2024-06-07 21:32
> Hellow, about the language change, the language displaying while playing anime is still romanji and that at keep watching also is romanji

Its fixed now

**Comment by Drac1652** [comment] 2024-06-07 21:37
Can i check on it now, or you still making some fixes and updates

**Comment by ErickLimaS** [comment] 2024-06-07 21:45
i havent done the pull request yet. i need to change the Latest Watched page a bit then i do the PR.

but some things is out now, like the language problem, on my hosted version https://aniproject-dev.vercel.app/

**Comment by Drac1652** [comment] 2024-06-07 21:51
> i havent done the pull request yet. i need to change the Latest Watched page a bit then i do the PR.
> 
> but some things is out now, like the language problem, on my hosted version https://aniproject-dev.vercel.app/

Okaay

**Comment by ErickLimaS** [comment] 2024-06-10 16:27
Its all fixed, so i will close this issue now.

**Closed by ErickLimaS** 2024-06-10 16:27 UTC
Labels: bug, enhancement
